spring.application.name=bookstore
 
spring.jpa.show-sql=true
#kertoo, mistä löytyy HAL formaatissa olevat REST palvelut
spring.data.rest.base-path=/rest
 
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
 
spring.datasource.url=jdbc:postgresql://localhost:5432/Bookstore
spring.datasource.username=postgres
spring.datasource.password=1234
 
#JPA/hibernate ei tee muutoksia ulkoiseen kantaan none arvolla
spring.jpa.hibernate.ddl-auto=none